name: Clojure CI

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Start server
      run: yarn http-server /public
